services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fastapi
    networks:
      - app-network

  fastapi:
    image: 682033466856.dkr.ecr.ap-southeast-1.amazonaws.com/fastproj-infra-dev/fastapi-app:latest
    platform: linux/amd64
    container_name: fastapi
    restart: always
    ports:
    - "8000:8000"
    networks:
      - app-network
    env_file:
      - .env

networks:
  app-network:
    driver: bridge
