services:
  fastapi:
    build:
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/fastapi_db"
    command: uvicorn main:app --host=0.0.0.0 --port=3000 --reload
    networks:
      - app-network

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fastapi_db
    volumes:
      - "./db/postgres_data:/var/lib/postgresql/data:rw"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
