name: Code CI

on: push

jobs:
  #----------------------------------------------
  #       Formatting and Linting
  #----------------------------------------------
  format-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
         python-version: '3.12'

      - uses: astral-sh/ruff-action@v3
      - run: ruff check --fix
      - run: ruff format

  #----------------------------------------------
  #       Security
  #----------------------------------------------
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif --severity-threshold=high
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
