name: Code CI

on: 
  push:
    branches:
      - main
      - 'releases/**'
  pull_request:
      types: [opened, synchronize, reopened]

jobs:
  #----------------------------------------------
  #       Formatting and Linting
  #----------------------------------------------
  format-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
         python-version: '3.12'

      - uses: astral-sh/ruff-action@v3
      - run: ruff check --fix
      - run: ruff format

  #----------------------------------------------
  #       Security
  #----------------------------------------------
  security:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif --severity-threshold=high
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif

  #----------------------------------------------
  #       SonarQube
  #----------------------------------------------
  sonarqube:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v5.2.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
