name: Formatting and Linting

on:
  push:
    branches:
      - main
      - 'releases/**'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  format-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
         python-version: '3.12'

      - uses: astral-sh/ruff-action@v3
      - run: ruff check --fix
      - run: ruff format
